const actionType = {
  SET_PRODUCT_ID: 'SET_PRODUCT_ID',
  SET_SEARCH_TERM: 'SET_SEARCH_TERM',
  DISPATCH_SEARCH_RESULTS: 'DISPATCH_SEARCH_RESULTS',
  DISPATCH_PRODUCT_DETAILS: 'DISPATCH_PRODUCT_DETAILS',
  SET_ACTIVE_SEARCH_PAGE: 'SET_ACTIVE_SEARCH_PAGE'
}

export default actionType
